sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

install:
  - mkdir -p build/logs
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - composer require --dev satooshi/php-coveralls -n

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs

after_success:
  - travis_retry vendor/bin/coveralls -v
